
project_id = "xfmguaamogzirnnqktwz"

[functions.receive-webhook]
verify_jwt = false

[functions.cleanup-duplicates]
verify_jwt = false

[functions.receive-property-details]
verify_jwt = false

[functions.sync-properties]
verify_jwt = false
